import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gonano",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-screen">
      <body
      
        className={`${montserrat.variable} antialiased h-full w-full min-w-[600px] `}
      >
        <Header/>
        <div className="pt-24">
          {children}
        </div>
        <footer className="w-full h-1/2 absolute min-w-[600px]">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
